facebook: 
  development: &default
    key: '271152339655027'
    secret: 594708d823a496004a0f7e5d50289dfd
  test: 
    <<: *default
  production:
    key: '471767956202786'
    secret: bd6574653119cabe38d31e5a8404e558

twitter: 
  development: &default
    key: 'kC8rorYKaTVJKEjOhPdA'
    secret: 8Lf32uzNDdFTQD0iZJUBPTksr5el4EEa8dD0IWqhM
  test: 
    <<: *default
  production:
    key: 'E7R1f65QeAOVUh1FvUXFIA'
    secret: tLfxJVynXQKhwHzd6fz0wcp4R8CQaAoEo5w7MDidudE