colors:
  report_options:
    - '#8B88FF'
    - '#FF9C00'
    - '#7BB31A'
    - '#EEDB00'
    - '#F87575'
    - '#456985'
    - '#FFCC79'
    - '#FF4D4D'
    - '#C4B51A'
    - '#E4E4E4'
    - '#B8E2E1'
    - '#FFCCFB'
    - '#74BD9A'
    - '#EE96FF'
    - '#A2A2A2'