ru:
  text: 
    "Мы проводим опрос. Будем благодарны за Ваше участие.
	Ссылка для перехода к опросу: {survey_link}

	Эта ссылка закреплена за данным опросом и Вашим адресом электронной почты.

	Благодарим за участие!"

en:
  text: 
    "Мы проводим опрос. Будем благодарны за Ваше участие.
	Ссылка для перехода к опросу: {survey_link}

	Эта ссылка закреплена за данным опросом и Вашим адресом электронной почты.

	Благодарим за участие!"